# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(1100, 800)
        TabWidget.setMinimumSize(QtCore.QSize(1100, 800))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        font.setKerning(True)
        TabWidget.setFont(font)
        TabWidget.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"\n"
"border-color: rgb(255, 170, 255);\n"
"")
        TabWidget.setDocumentMode(False)
        TabWidget.setTabsClosable(False)
        TabWidget.setMovable(False)
        TabWidget.setTabBarAutoHide(False)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(70, 370, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label.setObjectName("label")
        self.p1_modul = QtWidgets.QLineEdit(self.tab)
        self.p1_modul.setGeometry(QtCore.QRect(440, 370, 551, 31))
        self.p1_modul.setObjectName("p1_modul")
        self.p1_profil = QtWidgets.QLineEdit(self.tab)
        self.p1_profil.setGeometry(QtCore.QRect(440, 420, 551, 31))
        self.p1_profil.setObjectName("p1_profil")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(70, 420, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(70, 540, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(70, 610, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_5.setObjectName("label_5")
        self.p1_protokol = QtWidgets.QLineEdit(self.tab)
        self.p1_protokol.setGeometry(QtCore.QRect(170, 610, 131, 31))
        self.p1_protokol.setObjectName("p1_protokol")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(410, 610, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_6.setObjectName("label_6")
        self.p1_nomer = QtWidgets.QLineEdit(self.tab)
        self.p1_nomer.setGeometry(QtCore.QRect(440, 610, 31, 31))
        self.p1_nomer.setObjectName("p1_nomer")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(480, 610, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_7.setObjectName("label_7")
        self.p1_ot = QtWidgets.QLineEdit(self.tab)
        self.p1_ot.setGeometry(QtCore.QRect(520, 610, 121, 31))
        self.p1_ot.setObjectName("p1_ot")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(410, 650, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_8.setObjectName("label_8")
        self.p1_year = QtWidgets.QLineEdit(self.tab)
        self.p1_year.setGeometry(QtCore.QRect(470, 650, 41, 31))
        self.p1_year.setText("")
        self.p1_year.setObjectName("p1_year")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(640, 610, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(510, 650, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_12.setObjectName("label_12")
        self.p1_btnSend = QtWidgets.QPushButton(self.tab)
        self.p1_btnSend.setGeometry(QtCore.QRect(470, 200, 111, 41))
        self.p1_btnSend.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.p1_btnSend.setObjectName("p1_btnSend")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(340, 260, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_9.setObjectName("label_9")
        self.p1_document = QtWidgets.QLineEdit(self.tab)
        self.p1_document.setGeometry(QtCore.QRect(370, 140, 301, 31))
        self.p1_document.setObjectName("p1_document")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(380, 90, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_10.setObjectName("label_10")
        TabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(0, 270, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_15.setObjectName("label_15")
        self.p2_modul = QtWidgets.QLineEdit(self.tab_2)
        self.p2_modul.setGeometry(QtCore.QRect(220, 270, 371, 21))
        self.p2_modul.setObjectName("p2_modul")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(600, 270, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_16.setObjectName("label_16")
        self.p2_part = QtWidgets.QPlainTextEdit(self.tab_2)
        self.p2_part.setGeometry(QtCore.QRect(0, 300, 1071, 81))
        self.p2_part.setPlainText("")
        self.p2_part.setObjectName("p2_part")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(0, 390, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_17.setObjectName("label_17")
        self.p2_dicisplin = QtWidgets.QLineEdit(self.tab_2)
        self.p2_dicisplin.setGeometry(QtCore.QRect(520, 390, 251, 21))
        self.p2_dicisplin.setObjectName("p2_dicisplin")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(0, 420, 801, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.p2_predmetov = QtWidgets.QLineEdit(self.tab_2)
        self.p2_predmetov.setGeometry(QtCore.QRect(0, 460, 1071, 41))
        self.p2_predmetov.setText("")
        self.p2_predmetov.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p2_predmetov.setObjectName("p2_predmetov")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(0, 520, 871, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.p2_2dot2 = QtWidgets.QLineEdit(self.tab_2)
        self.p2_2dot2.setGeometry(QtCore.QRect(0, 560, 1071, 41))
        self.p2_2dot2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p2_2dot2.setObjectName("p2_2dot2")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(0, 610, 1001, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.p2_2dot3 = QtWidgets.QLineEdit(self.tab_2)
        self.p2_2dot3.setGeometry(QtCore.QRect(0, 660, 1071, 41))
        self.p2_2dot3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p2_2dot3.setObjectName("p2_2dot3")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(0, 220, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(10, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_22.setObjectName("label_22")
        self.p2_target = QtWidgets.QLineEdit(self.tab_2)
        self.p2_target.setGeometry(QtCore.QRect(60, 50, 1011, 21))
        self.p2_target.setObjectName("p2_target")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(10, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_23.setObjectName("label_23")
        self.p2_tasks = QtWidgets.QPlainTextEdit(self.tab_2)
        self.p2_tasks.setGeometry(QtCore.QRect(80, 80, 991, 131))
        self.p2_tasks.setObjectName("p2_tasks")
        TabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_24.setObjectName("label_24")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(50, 50, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_28.setObjectName("label_28")
        self.pIV_trud = QtWidgets.QLineEdit(self.tab_3)
        self.pIV_trud.setGeometry(QtCore.QRect(250, 390, 21, 21))
        self.pIV_trud.setObjectName("pIV_trud")
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(10, 390, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(10, 340, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(280, 390, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(540, 390, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(10, 420, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_34.setObjectName("label_34")
        self.pIV_hours = QtWidgets.QLineEdit(self.tab_3)
        self.pIV_hours.setGeometry(QtCore.QRect(410, 390, 41, 21))
        self.pIV_hours.setObjectName("pIV_hours")
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(460, 390, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_35.setObjectName("label_35")
        self.pIV_hoursEx = QtWidgets.QLineEdit(self.tab_3)
        self.pIV_hoursEx.setGeometry(QtCore.QRect(510, 390, 21, 21))
        self.pIV_hoursEx.setObjectName("pIV_hoursEx")
        self.pIV_form = QtWidgets.QLineEdit(self.tab_3)
        self.pIV_form.setGeometry(QtCore.QRect(230, 420, 21, 21))
        self.pIV_form.setObjectName("pIV_form")
        self.label_45 = QtWidgets.QLabel(self.tab_3)
        self.label_45.setGeometry(QtCore.QRect(20, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab_3)
        self.label_46.setGeometry(QtCore.QRect(160, 120, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        self.label_47.setGeometry(QtCore.QRect(390, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_47.setObjectName("label_47")
        self.t1_compet = QtWidgets.QPlainTextEdit(self.tab_3)
        self.t1_compet.setGeometry(QtCore.QRect(10, 170, 131, 101))
        self.t1_compet.setObjectName("t1_compet")
        self.t1_indicator = QtWidgets.QPlainTextEdit(self.tab_3)
        self.t1_indicator.setGeometry(QtCore.QRect(160, 170, 201, 101))
        self.t1_indicator.setObjectName("t1_indicator")
        self.t1_result = QtWidgets.QPlainTextEdit(self.tab_3)
        self.t1_result.setGeometry(QtCore.QRect(390, 170, 161, 101))
        self.t1_result.setObjectName("t1_result")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 280, 111, 41))
        self.pushButton_5.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        TabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_48 = QtWidgets.QLabel(self.tab_6)
        self.label_48.setGeometry(QtCore.QRect(50, 100, 31, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_48.setWordWrap(True)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_6)
        self.label_49.setGeometry(QtCore.QRect(80, 100, 191, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_49.setWordWrap(True)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_6)
        self.label_50.setGeometry(QtCore.QRect(270, 100, 71, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_50.setWordWrap(True)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_6)
        self.label_51.setGeometry(QtCore.QRect(340, 100, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_51.setWordWrap(True)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_6)
        self.label_52.setGeometry(QtCore.QRect(340, 150, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_52.setWordWrap(True)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_6)
        self.label_53.setGeometry(QtCore.QRect(620, 150, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_53.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_6)
        self.label_54.setGeometry(QtCore.QRect(340, 190, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_54.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_54.setWordWrap(True)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_6)
        self.label_55.setGeometry(QtCore.QRect(410, 190, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_55.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_6)
        self.label_56.setGeometry(QtCore.QRect(510, 190, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_56.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_56.setWordWrap(True)
        self.label_56.setObjectName("label_56")
        self.t2_razdel = QtWidgets.QPlainTextEdit(self.tab_6)
        self.t2_razdel.setGeometry(QtCore.QRect(80, 230, 191, 121))
        self.t2_razdel.setObjectName("t2_razdel")
        self.t2_semestr = QtWidgets.QPlainTextEdit(self.tab_6)
        self.t2_semestr.setGeometry(QtCore.QRect(270, 230, 71, 121))
        self.t2_semestr.setObjectName("t2_semestr")
        self.t2_lekci = QtWidgets.QPlainTextEdit(self.tab_6)
        self.t2_lekci.setGeometry(QtCore.QRect(340, 230, 71, 121))
        self.t2_lekci.setObjectName("t2_lekci")
        self.t2_seminar = QtWidgets.QPlainTextEdit(self.tab_6)
        self.t2_seminar.setGeometry(QtCore.QRect(410, 230, 101, 121))
        self.t2_seminar.setObjectName("t2_seminar")
        self.t2_consult = QtWidgets.QPlainTextEdit(self.tab_6)
        self.t2_consult.setGeometry(QtCore.QRect(510, 230, 111, 121))
        self.t2_consult.setObjectName("t2_consult")
        self.t1_compet_7 = QtWidgets.QPlainTextEdit(self.tab_6)
        self.t1_compet_7.setGeometry(QtCore.QRect(620, 230, 151, 121))
        self.t1_compet_7.setObjectName("t1_compet_7")
        self.t2_btnSend = QtWidgets.QPushButton(self.tab_6)
        self.t2_btnSend.setGeometry(QtCore.QRect(790, 390, 111, 41))
        self.t2_btnSend.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.t2_btnSend.setObjectName("t2_btnSend")
        self.label_57 = QtWidgets.QLabel(self.tab_6)
        self.label_57.setGeometry(QtCore.QRect(770, 100, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_57.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_57.setWordWrap(True)
        self.label_57.setObjectName("label_57")
        self.t1_compet_8 = QtWidgets.QPlainTextEdit(self.tab_6)
        self.t1_compet_8.setGeometry(QtCore.QRect(770, 230, 131, 121))
        self.t1_compet_8.setObjectName("t1_compet_8")
        self.t2_razdel_2 = QtWidgets.QPlainTextEdit(self.tab_6)
        self.t2_razdel_2.setGeometry(QtCore.QRect(50, 230, 31, 121))
        self.t2_razdel_2.setObjectName("t2_razdel_2")
        self.t2_btnToSend = QtWidgets.QPushButton(self.tab_6)
        self.t2_btnToSend.setGeometry(QtCore.QRect(950, 710, 111, 41))
        self.t2_btnToSend.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.t2_btnToSend.setObjectName("t2_btnToSend")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(50, 20, 981, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        TabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_58 = QtWidgets.QLabel(self.tab_5)
        self.label_58.setGeometry(QtCore.QRect(50, 90, 71, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_58.setWordWrap(True)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_5)
        self.label_59.setGeometry(QtCore.QRect(120, 90, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_59.setWordWrap(True)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_5)
        self.label_60.setGeometry(QtCore.QRect(240, 90, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_60.setWordWrap(True)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_5)
        self.label_61.setGeometry(QtCore.QRect(240, 110, 171, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_61.setWordWrap(True)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_5)
        self.label_62.setGeometry(QtCore.QRect(410, 110, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_62.setWordWrap(True)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_5)
        self.label_63.setGeometry(QtCore.QRect(510, 110, 71, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_63.setWordWrap(True)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.tab_5)
        self.label_64.setGeometry(QtCore.QRect(580, 90, 101, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_64.setWordWrap(True)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.tab_5)
        self.label_65.setGeometry(QtCore.QRect(680, 90, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_65.setWordWrap(True)
        self.label_65.setObjectName("label_65")
        self.t3_semestr = QtWidgets.QPlainTextEdit(self.tab_5)
        self.t3_semestr.setGeometry(QtCore.QRect(50, 210, 71, 111))
        self.t3_semestr.setObjectName("t3_semestr")
        self.t3_nazvanie = QtWidgets.QPlainTextEdit(self.tab_5)
        self.t3_nazvanie.setGeometry(QtCore.QRect(120, 210, 121, 111))
        self.t3_nazvanie.setObjectName("t3_nazvanie")
        self.t3_vid = QtWidgets.QPlainTextEdit(self.tab_5)
        self.t3_vid.setGeometry(QtCore.QRect(240, 210, 171, 111))
        self.t3_vid.setObjectName("t3_vid")
        self.t3_sroki = QtWidgets.QPlainTextEdit(self.tab_5)
        self.t3_sroki.setGeometry(QtCore.QRect(410, 210, 101, 111))
        self.t3_sroki.setObjectName("t3_sroki")
        self.t3_zatrat = QtWidgets.QPlainTextEdit(self.tab_5)
        self.t3_zatrat.setGeometry(QtCore.QRect(510, 210, 71, 111))
        self.t3_zatrat.setObjectName("t3_zatrat")
        self.t3_ocenka = QtWidgets.QPlainTextEdit(self.tab_5)
        self.t3_ocenka.setGeometry(QtCore.QRect(580, 210, 101, 111))
        self.t3_ocenka.setObjectName("t3_ocenka")
        self.t3_uchebn = QtWidgets.QPlainTextEdit(self.tab_5)
        self.t3_uchebn.setGeometry(QtCore.QRect(680, 210, 141, 111))
        self.t3_uchebn.setObjectName("t3_uchebn")
        self.t2_btnSend_2 = QtWidgets.QPushButton(self.tab_5)
        self.t2_btnSend_2.setGeometry(QtCore.QRect(710, 360, 111, 41))
        self.t2_btnSend_2.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.t2_btnSend_2.setObjectName("t2_btnSend_2")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(50, 50, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_27.setObjectName("label_27")
        self.t3_btnSend = QtWidgets.QPushButton(self.tab_5)
        self.t3_btnSend.setGeometry(QtCore.QRect(890, 680, 111, 41))
        self.t3_btnSend.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.t3_btnSend.setObjectName("t3_btnSend")
        TabWidget.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_66 = QtWidgets.QLabel(self.tab_7)
        self.label_66.setGeometry(QtCore.QRect(70, 100, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_66.setWordWrap(True)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.tab_7)
        self.label_67.setGeometry(QtCore.QRect(70, 150, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_67.setWordWrap(True)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.tab_7)
        self.label_68.setGeometry(QtCore.QRect(70, 210, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_68.setWordWrap(True)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.tab_7)
        self.label_69.setGeometry(QtCore.QRect(70, 260, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_69.setWordWrap(True)
        self.label_69.setObjectName("label_69")
        self.p3_trud = QtWidgets.QPlainTextEdit(self.tab_7)
        self.p3_trud.setGeometry(QtCore.QRect(230, 100, 441, 51))
        self.p3_trud.setObjectName("p3_trud")
        self.p3_name = QtWidgets.QPlainTextEdit(self.tab_7)
        self.p3_name.setGeometry(QtCore.QRect(230, 150, 441, 61))
        self.p3_name.setObjectName("p3_name")
        self.p3_forma = QtWidgets.QPlainTextEdit(self.tab_7)
        self.p3_forma.setGeometry(QtCore.QRect(230, 210, 441, 51))
        self.p3_forma.setObjectName("p3_forma")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.tab_7)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(230, 260, 441, 61))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_26 = QtWidgets.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(70, 60, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_26.setObjectName("label_26")
        TabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_70 = QtWidgets.QLabel(self.tab_8)
        self.label_70.setGeometry(QtCore.QRect(30, 50, 41, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_70.setWordWrap(True)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.tab_8)
        self.label_71.setGeometry(QtCore.QRect(70, 50, 111, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setWordWrap(True)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.tab_8)
        self.label_72.setGeometry(QtCore.QRect(180, 50, 201, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setWordWrap(True)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.tab_8)
        self.label_73.setGeometry(QtCore.QRect(380, 50, 111, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setWordWrap(True)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab_8)
        self.label_74.setGeometry(QtCore.QRect(490, 50, 111, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setWordWrap(True)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.tab_8)
        self.label_75.setGeometry(QtCore.QRect(600, 50, 111, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setWordWrap(True)
        self.label_75.setObjectName("label_75")
        self.t4_nomer = QtWidgets.QPlainTextEdit(self.tab_8)
        self.t4_nomer.setGeometry(QtCore.QRect(70, 180, 111, 111))
        self.t4_nomer.setObjectName("t4_nomer")
        self.t4_name = QtWidgets.QPlainTextEdit(self.tab_8)
        self.t4_name.setGeometry(QtCore.QRect(180, 180, 201, 111))
        self.t4_name.setObjectName("t4_name")
        self.t4_trud = QtWidgets.QPlainTextEdit(self.tab_8)
        self.t4_trud.setGeometry(QtCore.QRect(380, 180, 111, 111))
        self.t4_trud.setObjectName("t4_trud")
        self.t4_ocenka = QtWidgets.QPlainTextEdit(self.tab_8)
        self.t4_ocenka.setGeometry(QtCore.QRect(490, 180, 111, 111))
        self.t4_ocenka.setObjectName("t4_ocenka")
        self.t4_form = QtWidgets.QPlainTextEdit(self.tab_8)
        self.t4_form.setGeometry(QtCore.QRect(600, 180, 111, 111))
        self.t4_form.setObjectName("t4_form")
        self.t4_btnSend = QtWidgets.QPushButton(self.tab_8)
        self.t4_btnSend.setGeometry(QtCore.QRect(600, 340, 111, 41))
        self.t4_btnSend.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.t4_btnSend.setObjectName("t4_btnSend")
        self.label_25 = QtWidgets.QLabel(self.tab_8)
        self.label_25.setGeometry(QtCore.QRect(40, 10, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_25.setObjectName("label_25")
        self.label_98 = QtWidgets.QLabel(self.tab_8)
        self.label_98.setGeometry(QtCore.QRect(30, 180, 41, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_98.setFont(font)
        self.label_98.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setWordWrap(True)
        self.label_98.setObjectName("label_98")
        TabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_76 = QtWidgets.QLabel(self.tab_9)
        self.label_76.setGeometry(QtCore.QRect(20, 30, 841, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_76.setWordWrap(True)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.tab_9)
        self.label_77.setGeometry(QtCore.QRect(20, 100, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setWordWrap(True)
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.tab_9)
        self.label_78.setGeometry(QtCore.QRect(80, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setWordWrap(True)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.tab_9)
        self.label_79.setGeometry(QtCore.QRect(230, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_79.setFont(font)
        self.label_79.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setWordWrap(True)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.tab_9)
        self.label_80.setGeometry(QtCore.QRect(380, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setWordWrap(True)
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.tab_9)
        self.label_81.setGeometry(QtCore.QRect(530, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setWordWrap(True)
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.tab_9)
        self.label_82.setGeometry(QtCore.QRect(20, 170, 61, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_82.setFont(font)
        self.label_82.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setWordWrap(True)
        self.label_82.setObjectName("label_82")
        self.t5_tema = QtWidgets.QPlainTextEdit(self.tab_9)
        self.t5_tema.setGeometry(QtCore.QRect(80, 170, 151, 141))
        self.t5_tema.setObjectName("t5_tema")
        self.t5_zadanie = QtWidgets.QPlainTextEdit(self.tab_9)
        self.t5_zadanie.setGeometry(QtCore.QRect(230, 170, 151, 141))
        self.t5_zadanie.setObjectName("t5_zadanie")
        self.t5_form = QtWidgets.QPlainTextEdit(self.tab_9)
        self.t5_form.setGeometry(QtCore.QRect(380, 170, 151, 141))
        self.t5_form.setObjectName("t5_form")
        self.t5_idk = QtWidgets.QPlainTextEdit(self.tab_9)
        self.t5_idk.setGeometry(QtCore.QRect(530, 170, 151, 141))
        self.t5_idk.setObjectName("t5_idk")
        self.t4_btnSend_2 = QtWidgets.QPushButton(self.tab_9)
        self.t4_btnSend_2.setGeometry(QtCore.QRect(570, 350, 111, 41))
        self.t4_btnSend_2.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.t4_btnSend_2.setObjectName("t4_btnSend_2")
        TabWidget.addTab(self.tab_9, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setGeometry(QtCore.QRect(10, 20, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(10, 100, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        self.label_38.setGeometry(QtCore.QRect(10, 170, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setGeometry(QtCore.QRect(10, 260, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_39.setObjectName("label_39")
        self.label_44 = QtWidgets.QLabel(self.tab_4)
        self.label_44.setGeometry(QtCore.QRect(10, 350, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_44.setObjectName("label_44")
        self.p4_45 = QtWidgets.QPlainTextEdit(self.tab_4)
        self.p4_45.setGeometry(QtCore.QRect(520, 20, 551, 61))
        self.p4_45.setObjectName("p4_45")
        self.p4_main = QtWidgets.QPlainTextEdit(self.tab_4)
        self.p4_main.setGeometry(QtCore.QRect(290, 170, 781, 71))
        self.p4_main.setObjectName("p4_main")
        self.p4_dop = QtWidgets.QPlainTextEdit(self.tab_4)
        self.p4_dop.setGeometry(QtCore.QRect(290, 260, 781, 71))
        self.p4_dop.setObjectName("p4_dop")
        self.p4_period = QtWidgets.QPlainTextEdit(self.tab_4)
        self.p4_period.setGeometry(QtCore.QRect(290, 350, 781, 71))
        self.p4_period.setObjectName("p4_period")
        TabWidget.addTab(self.tab_4, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_83 = QtWidgets.QLabel(self.tab_10)
        self.label_83.setGeometry(QtCore.QRect(40, 150, 61, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setWordWrap(True)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.tab_10)
        self.label_84.setGeometry(QtCore.QRect(40, 80, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setWordWrap(True)
        self.label_84.setObjectName("label_84")
        self.t6_btnAdd = QtWidgets.QPushButton(self.tab_10)
        self.t6_btnAdd.setGeometry(QtCore.QRect(590, 330, 111, 41))
        self.t6_btnAdd.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.t6_btnAdd.setObjectName("t6_btnAdd")
        self.t6_vid = QtWidgets.QPlainTextEdit(self.tab_10)
        self.t6_vid.setGeometry(QtCore.QRect(250, 150, 151, 141))
        self.t6_vid.setObjectName("t6_vid")
        self.label_85 = QtWidgets.QLabel(self.tab_10)
        self.label_85.setGeometry(QtCore.QRect(550, 80, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setWordWrap(True)
        self.label_85.setObjectName("label_85")
        self.t6_hours = QtWidgets.QPlainTextEdit(self.tab_10)
        self.t6_hours.setGeometry(QtCore.QRect(550, 150, 151, 141))
        self.t6_hours.setObjectName("t6_hours")
        self.label_86 = QtWidgets.QLabel(self.tab_10)
        self.label_86.setGeometry(QtCore.QRect(250, 80, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_86.setFont(font)
        self.label_86.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setWordWrap(True)
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.tab_10)
        self.label_87.setGeometry(QtCore.QRect(100, 80, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_87.setFont(font)
        self.label_87.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setWordWrap(True)
        self.label_87.setObjectName("label_87")
        self.t6_tema = QtWidgets.QPlainTextEdit(self.tab_10)
        self.t6_tema.setGeometry(QtCore.QRect(100, 150, 151, 141))
        self.t6_tema.setObjectName("t6_tema")
        self.t6_form = QtWidgets.QPlainTextEdit(self.tab_10)
        self.t6_form.setGeometry(QtCore.QRect(400, 150, 151, 141))
        self.t6_form.setObjectName("t6_form")
        self.label_88 = QtWidgets.QLabel(self.tab_10)
        self.label_88.setGeometry(QtCore.QRect(400, 80, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_88.setFont(font)
        self.label_88.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setWordWrap(True)
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.tab_10)
        self.label_89.setGeometry(QtCore.QRect(40, 30, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_89.setFont(font)
        self.label_89.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_89.setObjectName("label_89")
        self.t6_btnSend = QtWidgets.QPushButton(self.tab_10)
        self.t6_btnSend.setGeometry(QtCore.QRect(950, 710, 111, 41))
        self.t6_btnSend.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.t6_btnSend.setObjectName("t6_btnSend")
        TabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.t7_vid = QtWidgets.QPlainTextEdit(self.tab_11)
        self.t7_vid.setGeometry(QtCore.QRect(100, 150, 151, 141))
        self.t7_vid.setObjectName("t7_vid")
        self.t7_com = QtWidgets.QPlainTextEdit(self.tab_11)
        self.t7_com.setGeometry(QtCore.QRect(400, 150, 171, 141))
        self.t7_com.setObjectName("t7_com")
        self.label_90 = QtWidgets.QLabel(self.tab_11)
        self.label_90.setGeometry(QtCore.QRect(40, 80, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_90.setFont(font)
        self.label_90.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setWordWrap(True)
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.tab_11)
        self.label_91.setGeometry(QtCore.QRect(400, 80, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_91.setFont(font)
        self.label_91.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setWordWrap(True)
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.tab_11)
        self.label_92.setGeometry(QtCore.QRect(40, 150, 61, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_92.setFont(font)
        self.label_92.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setWordWrap(True)
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.tab_11)
        self.label_93.setGeometry(QtCore.QRect(250, 80, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_93.setFont(font)
        self.label_93.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setWordWrap(True)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.tab_11)
        self.label_94.setGeometry(QtCore.QRect(100, 80, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_94.setFont(font)
        self.label_94.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(255, 170, 255);\n"
"border-style: solid;\n"
" border-width: 1px;\n"
" border-color: black; ")
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setWordWrap(True)
        self.label_94.setObjectName("label_94")
        self.t7_contr = QtWidgets.QPlainTextEdit(self.tab_11)
        self.t7_contr.setGeometry(QtCore.QRect(250, 150, 151, 141))
        self.t7_contr.setObjectName("t7_contr")
        self.t7_btnAdd = QtWidgets.QPushButton(self.tab_11)
        self.t7_btnAdd.setGeometry(QtCore.QRect(460, 330, 111, 41))
        self.t7_btnAdd.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.t7_btnAdd.setObjectName("t7_btnAdd")
        self.label_95 = QtWidgets.QLabel(self.tab_11)
        self.label_95.setGeometry(QtCore.QRect(40, 30, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_95.setFont(font)
        self.label_95.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_95.setObjectName("label_95")
        TabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.label_96 = QtWidgets.QLabel(self.tab_12)
        self.label_96.setGeometry(QtCore.QRect(390, 50, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_96.setFont(font)
        self.label_96.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_96.setObjectName("label_96")
        self.p5_demka = QtWidgets.QPlainTextEdit(self.tab_12)
        self.p5_demka.setGeometry(QtCore.QRect(320, 100, 421, 561))
        self.p5_demka.setObjectName("p5_demka")
        TabWidget.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.label_97 = QtWidgets.QLabel(self.tab_13)
        self.label_97.setGeometry(QtCore.QRect(310, 10, 461, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_97.setFont(font)
        self.label_97.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_97.setObjectName("label_97")
        self.p6_82 = QtWidgets.QPlainTextEdit(self.tab_13)
        self.p6_82.setGeometry(QtCore.QRect(340, 150, 391, 531))
        self.p6_82.setObjectName("p6_82")
        self.p6_btnSend = QtWidgets.QPushButton(self.tab_13)
        self.p6_btnSend.setGeometry(QtCore.QRect(480, 710, 111, 41))
        self.p6_btnSend.setStyleSheet("\n"
"background-color: rgb(170, 255, 255);")
        self.p6_btnSend.setObjectName("p6_btnSend")
        TabWidget.addTab(self.tab_13, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        self.label.setText(_translate("TabWidget", "Наименование дисциплины (модуля)"))
        self.label_3.setText(_translate("TabWidget", "Направленность (профиль) подготовки"))
        self.label_4.setText(_translate("TabWidget", "Согласовано с УМК факультета сервиса и рекламы"))
        self.label_5.setText(_translate("TabWidget", "Протокол"))
        self.label_6.setText(_translate("TabWidget", "№"))
        self.label_7.setText(_translate("TabWidget", "от<"))
        self.label_8.setText(_translate("TabWidget", "Год 20"))
        self.label_11.setText(_translate("TabWidget", ">"))
        self.label_12.setText(_translate("TabWidget", "г."))
        self.p1_btnSend.setText(_translate("TabWidget", "Создать"))
        self.label_9.setText(_translate("TabWidget", "Рабочая программа дисциплины (модуля)"))
        self.label_10.setText(_translate("TabWidget", "Введите название документа"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Стр 1"))
        self.label_14.setText(_translate("TabWidget", "I. Цели и задачи дисциплины (модуля)"))
        self.label_15.setText(_translate("TabWidget", "2.1. Учебная дисциплина (модуль)"))
        self.label_16.setText(_translate("TabWidget", "относится к части,"))
        self.label_17.setText(_translate("TabWidget", "Наименования дисциплин, необходимых для освоения данной учебной дисциплины:"))
        self.label_18.setText(_translate("TabWidget", "Знания и навыки, полученные обучающимися в курсе дисциплины, могут оказаться полезными при изучении следующих предметов:"))
        self.label_19.setText(_translate("TabWidget", "2.2. Для изучения данной учебной дисциплины (модуля) необходимы знания, умения и навыки, формируемые предшествующими дисциплинами:"))
        self.label_20.setText(_translate("TabWidget", "2.3. Перечень последующих учебных дисциплин, для которых необходимы знания, умения и навыки, формируемые данной учебной дисциплиной:"))
        self.label_21.setText(_translate("TabWidget", "II. МЕСТО ДИСЦИПЛИНЫ В СТРУКТУРЕ ОПОП ВО"))
        self.label_22.setText(_translate("TabWidget", "Цели"))
        self.label_23.setText(_translate("TabWidget", "Задачи"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "Стр 2"))
        self.label_24.setText(_translate("TabWidget", "III. ТРЕБОВАНИЯ К РЕЗУЛЬТАТАМ ОСВОЕНИЯ ДИСЦИПЛИНЫ"))
        self.label_28.setText(_translate("TabWidget", "Перечень планируемых результатов обучения по дисциплине (модулю),\n"
" соотнесенных с индикаторами достижения компетенций"))
        self.label_30.setText(_translate("TabWidget", "Трудоемкость дисциплины составляет"))
        self.label_31.setText(_translate("TabWidget", "IV. СОДЕРЖАНИЕ И СТРУКТУРА ДИСЦИПЛИНЫ"))
        self.label_32.setText(_translate("TabWidget", " зачетных единиц,"))
        self.label_33.setText(_translate("TabWidget", "часов на экзамен"))
        self.label_34.setText(_translate("TabWidget", "Форма промежуточной аттестации"))
        self.label_35.setText(_translate("TabWidget", "часов,"))
        self.label_45.setText(_translate("TabWidget", "Компетенция"))
        self.label_46.setText(_translate("TabWidget", "Индикаторы компетенций"))
        self.label_47.setText(_translate("TabWidget", "Результаты обучения"))
        self.pushButton_5.setText(_translate("TabWidget", "Добавить"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "Стр 3"))
        self.label_48.setText(_translate("TabWidget", "п/п"))
        self.label_49.setText(_translate("TabWidget", "Раздел дисциплины/темы"))
        self.label_50.setText(_translate("TabWidget", "Семестр"))
        self.label_51.setText(_translate("TabWidget", "Виды учебной работы, включая самостоятельную работу обучающихся и трудоемкость\n"
"(в часах)\n"
""))
        self.label_52.setText(_translate("TabWidget", "Контактная работа преподавателя с обучающимися"))
        self.label_53.setText(_translate("TabWidget", "Самостоятельная\n"
"работа\n"
""))
        self.label_54.setText(_translate("TabWidget", "Лекции"))
        self.label_55.setText(_translate("TabWidget", "Семинарские"))
        self.label_56.setText(_translate("TabWidget", "Консультации"))
        self.t2_btnSend.setText(_translate("TabWidget", "Добавить"))
        self.label_57.setText(_translate("TabWidget", "Формы текущего контроля успеваемости;\n"
"Форма промежуточной аттестации\n"
"(по семестрам)\n"
""))
        self.t2_btnToSend.setText(_translate("TabWidget", "Отправить"))
        self.label_29.setText(_translate("TabWidget", "4.1 Содержание дисциплины, структурированное по темам, c указанием видов учебных занятий и отведенного на них количества академических часов"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_6), _translate("TabWidget", "Стр 4"))
        self.label_58.setText(_translate("TabWidget", "Семестр"))
        self.label_59.setText(_translate("TabWidget", "Название раздела, темы"))
        self.label_60.setText(_translate("TabWidget", "Самостоятельная работа обучающихся"))
        self.label_61.setText(_translate("TabWidget", "Вид самостоятельной работы"))
        self.label_62.setText(_translate("TabWidget", "Сроки выполнения"))
        self.label_63.setText(_translate("TabWidget", "Затраты времени (час.)"))
        self.label_64.setText(_translate("TabWidget", "Оценочное средство"))
        self.label_65.setText(_translate("TabWidget", "Учебно-методическое обеспечение самостоятельной работы "))
        self.t2_btnSend_2.setText(_translate("TabWidget", "Добавить"))
        self.label_27.setText(_translate("TabWidget", "4.2 План внеаудиторной самостоятельной работы обучающихся по дисциплине"))
        self.t3_btnSend.setText(_translate("TabWidget", "Отправить"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_5), _translate("TabWidget", "Стр 5"))
        self.label_66.setText(_translate("TabWidget", "Трудоемкость дисциплины (з.е.)"))
        self.label_67.setText(_translate("TabWidget", "Наименование основных разделов (модулей)"))
        self.label_68.setText(_translate("TabWidget", "Формы текущего контроля"))
        self.label_69.setText(_translate("TabWidget", "Форма промежуточной аттестации"))
        self.label_26.setText(_translate("TabWidget", "4.3 Содержание учебного материала"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_7), _translate("TabWidget", "Стр 6"))
        self.label_70.setText(_translate("TabWidget", "п/п"))
        self.label_71.setText(_translate("TabWidget", "№ раздела и темы дисциплины (модуля)"))
        self.label_72.setText(_translate("TabWidget", "Наименование семинаров, практических и лабораторных работ"))
        self.label_73.setText(_translate("TabWidget", "Трудоемкость\n"
"(час.)\n"
""))
        self.label_74.setText(_translate("TabWidget", "Оценочные средства"))
        self.label_75.setText(_translate("TabWidget", "Формируемые компетенции"))
        self.t4_btnSend.setText(_translate("TabWidget", "Добавить"))
        self.label_25.setText(_translate("TabWidget", "4.3.1. Перечень семинарских, практических занятий и лабораторных работ"))
        self.label_98.setText(_translate("TabWidget", "Авто"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_8), _translate("TabWidget", "Стр 7"))
        self.label_76.setText(_translate("TabWidget", "4.3.2. Перечень тем (вопросов), выносимых на самостоятельное изучение самостоятельной работы студентов\n"
""))
        self.label_77.setText(_translate("TabWidget", "№      п/п"))
        self.label_78.setText(_translate("TabWidget", "Тема"))
        self.label_79.setText(_translate("TabWidget", "Задание"))
        self.label_80.setText(_translate("TabWidget", "Формируемая компетенция"))
        self.label_81.setText(_translate("TabWidget", "ИДК"))
        self.label_82.setText(_translate("TabWidget", "Авто"))
        self.t4_btnSend_2.setText(_translate("TabWidget", "Добавить"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_9), _translate("TabWidget", "Стр 8"))
        self.label_36.setText(_translate("TabWidget", "4.5. Примерная тематика курсовых работ (проектов)"))
        self.label_37.setText(_translate("TabWidget", "V. УЧЕБНО-МЕТОДИЧЕСКОЕ И ИНФОРМАЦИОННОЕ \n"
" ОБЕСПЕЧЕНИЕ ДИСЦИПЛИНЫ (МОДУЛЯ)"))
        self.label_38.setText(_translate("TabWidget", "а) основная литература"))
        self.label_39.setText(_translate("TabWidget", "б) дополнительная литература"))
        self.label_44.setText(_translate("TabWidget", "в) периодическая литература"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_4), _translate("TabWidget", "Стр 9"))
        self.label_83.setText(_translate("TabWidget", "Авто"))
        self.label_84.setText(_translate("TabWidget", "№      п/п"))
        self.t6_btnAdd.setText(_translate("TabWidget", "Добавить"))
        self.label_85.setText(_translate("TabWidget", "Кол-во часов"))
        self.label_86.setText(_translate("TabWidget", "Вид занятия"))
        self.label_87.setText(_translate("TabWidget", "Тема занятия"))
        self.label_88.setText(_translate("TabWidget", "Форма / Методы интерактивного обучения"))
        self.label_89.setText(_translate("TabWidget", "Наименование тем занятий с использованием активных форм обучения:"))
        self.t6_btnSend.setText(_translate("TabWidget", "Отправить"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_10), _translate("TabWidget", "Стр 10"))
        self.label_90.setText(_translate("TabWidget", "№      п/п"))
        self.label_91.setText(_translate("TabWidget", "Компетенции, компоненты которых контролируются\n"
"\n"
""))
        self.label_92.setText(_translate("TabWidget", "Авто"))
        self.label_93.setText(_translate("TabWidget", "Контролируемые темы (разделы)"))
        self.label_94.setText(_translate("TabWidget", "Вид контроля"))
        self.t7_btnAdd.setText(_translate("TabWidget", "Добавить"))
        self.label_95.setText(_translate("TabWidget", "8.1. Оценочные средства текущего контроля"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_11), _translate("TabWidget", "Стр 11"))
        self.label_96.setText(_translate("TabWidget", "Демонстрационный вариант теста №1"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_12), _translate("TabWidget", "Стр 12"))
        self.label_97.setText(_translate("TabWidget", "8.2. Оценочные средства для промежуточной аттестации\n"
" \n"
" \n"
"Примерный перечень вопросов и заданий к экзамену (зачету)\n"
"Вопросы к экзамену.\n"
""))
        self.p6_btnSend.setText(_translate("TabWidget", "Завершить"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_13), _translate("TabWidget", "Стр 13"))


